spring.application.name=auth-service
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/citylens_auth_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true 

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

server.error.include-message=always

user-service.url=${USER_SERVICE_URL:http://localhost:8083}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=citylensadmin@gmail.com
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

frontend.url=http://localhost:5173




