spring.application.name=gateway-service
server.port=9000

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=${AUTH_URI:http://localhost:8082}
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**


spring.cloud.gateway.routes[1].id=user-service
spring.cloud.gateway.routes[1].uri=${USER_URI:http://localhost:8083}
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/users/**


spring.cloud.gateway.routes[2].id=location-service
spring.cloud.gateway.routes[2].uri=${LOCATION_URI:http://localhost:8084}
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/locations/**


spring.cloud.gateway.routes[3].id=weather-service
spring.cloud.gateway.routes[3].uri=${WEATHER_URI:http://localhost:8085}
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/weather/**


spring.cloud.gateway.routes[4].id=favorites-service
spring.cloud.gateway.routes[4].uri=${USER_URI:http://localhost:8083}
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/favorites/**


spring.cloud.gateway.routes[5].id=itinerary-service
spring.cloud.gateway.routes[5].uri=${LOCATION_URI:http://localhost:8084}
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/itinerary/**


spring.cloud.gateway.routes[6].id=itineraries-service
spring.cloud.gateway.routes[6].uri=${USER_URI:http://localhost:8083}
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/itineraries/**


spring.cloud.gateway.routes[7].id=admin-service
spring.cloud.gateway.routes[7].uri=${AUTH_URI:http://localhost:8082}
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/admin/**


spring.cloud.gateway.routes[8].id=ai-service
spring.cloud.gateway.routes[8].uri=${AI_URI:http://localhost:8000}
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/ai/**



